Do not link against clang or llvm libraries.
In in-source builds we have all clang and llvm libraries as targets.
We should not link against them because this causes double initialization
of statics when the plugin is dlopened by clang.

Depending on what clang initializes we can get:
"CommandLine Error: Option 'pass-remarks' registered more than once!
fatal error: error in backend: inconsistency in registered CommandLine options"